### ISSUE TITLE
Server profile update fails

### ISSUE THREAD

**Issue by OneHungryPoboy** [hexparrot/mineos#100]
Running Mineos plugin on Freenas 9.3
Updated to the last build today (matched build shown in github master) now no server profiles will update, including stock profiles.  reverting to default plugin version allowed them to work again.

**Comment by hexparrot** [comment]
Issue introduced in recent commit https://github.com/hexparrot/mineos/pull/101

The offending commit has been reverted.  Update to the most recent commit now 378eeb29c2845625e443a044f18f0fe8cde25731 and it should be resolved.
