### ISSUE TITLE
misc.base_directory is ignored when passing commands to mineos_console.py

### ISSUE THREAD

**Issue by idkw** [hexparrot/mineos#105]
I changed the default base_directory of mineos from /var/games/minecraft to /home/myname/mineos inside the file /etc/mineos.conf
It works when managing servers from the web ui.
But when I try to run a command from linux console using : 

cd /usr/games/minecraft
./mineos_console.py -s myserver get port

It outputs the following error : 

Traceback (most recent call last):
  File "./mineos_console.py", line 87, in <module>
    instance._command_stuff(text)
  File "/usr/games/minecraft/mineos.py", line 46, in wrapper
    raise RuntimeWarning('Ignoring {%s}: server not found "%s"' % (fn.__name__,self.server_name))
RuntimeWarning: Ignoring {_command_stuff}: server not found "myserver"

Thus I cannot make scheduled restarts or any command with crontabs

**Comment by hexparrot** [comment]
Correct, ./mineos_console.py doesn't actually use the value in mineos.conf, but instead just *incidentally* uses the /var/games/minecraft directory.  The mineos.conf file, for example, pretty much only has information the web-ui uses (thus why ignored by the mineos_console) with the exception of this one attribute.

It can be changed at runtime, however, using the -d flag:

./mineos_console.poy -s myserver -d /home/myname/mineos get port

https://github.com/hexparrot/mineos/blob/master/mineos_console.py#L24

**Comment by idkw** [comment]
Thanks !
