### ISSUE TITLE
Keep logged in

### ISSUE THREAD

**Issue by idkw** [hexparrot/mineos#107]
Hello

When you have a page opened for a few minutes, the session expires but it does not returns to the login page unless refreshing. Could you add an checkbox when logging in to allow to stay logged in forever, because it is annoying to log in every time ?

Thanks

**Comment by hexparrot** [comment]
I've never had this issue, though all the usage and testing of the web-ui.  By default, the timeout is 60 minutes, which is substantially more than the few minutes you're saying...and each 60 minutes is refreshed whenever you do...anything.  Perhaps it's your browser?

"CherryPy defaults to a 60-minute session timeout, which also applies to the cookie which is sent to the client. Unfortunately, some versions of Safari (“4 public beta” on Windows XP at least) appear to have a bug in their parsing of the GMT expiration date–they appear to interpret the date as one hour in the past. Sixty minutes minus one hour is pretty close to zero, so you may experience this bug as a new session id for every request, unless the requests are less than one second apart. To fix, try increasing the session.timeout." - http://cherrypy.readthedocs.org/en/latest/pkg/cherrypy.lib.html

However, if you feel the need to increase or manually modify this value, follow the instructions here:

http://discourse.codeemo.com/t/solved-adjust-default-time-out-for-web-ui/324

**Comment by idkw** [comment]
Thanks for the link : http://discourse.codeemo.com/t/solved-adjust-default-time-out-for-web-ui/324
That's what I was looking for, when saying "few minutes" I was saying 60 minutes I think ^^
I just need to last forever so I'll put a big number.

**Comment by hexparrot** [comment]
Glad it worked out.  If you have any other questions or concerns, don't hestitate to let me know either here or in the discourse.codeemo.com support forums.
