### ISSUE TITLE
dosent work on CentOS 7

### ISSUE THREAD

**Issue by Hoijima** [hexparrot/mineos#108]
Used the manual.
Service dosent start at all.

Anyway i can run debug on this thing to find out reasons?

**Comment by hexparrot** [comment]
As root:

cd /usr/games/minecraft
./server.py

**Comment by Hoijima** [comment]
[root@mshade ~]# service mineos start
Traceback (most recent call last):
  File "/usr/games/minecraft/server.py", line 11, in <module>
    import cherrypy
ImportError: No module named cherrypy

i had to delete the null outputs/ Sorry


i can import cherrypy in python console

i installed your way the 3.2.2 | why not use rpm packages?

and installed 3.30 from the suse distro, same result

the server alone work's fine , but it's useless if it can't run as service

**Comment by hexparrot** [comment]
You can install cherrypy any way you please, from source, RPM...etc.  Any way you choose, provided that you get a version that is no newer than 3.2.x.

See http://discourse.codeemo.com/t/solved-ssl-received-a-record-that-exceeded-the-maximum-permissible-length/45/2?u=hexparrot

**Comment by Hoijima** [comment]
[root@mshade setuptools-1.4.2]# pip2 install cherrypy==3.2.3
Collecting cherrypy==3.2.3
  Downloading CherryPy-3.2.3.tar.gz (423kB)
    100% |################################| 425kB 705kB/s
Installing collected packages: cherrypy
  Found existing installation: CherryPy 3.2.2
    Uninstalling CherryPy-3.2.2:
      Successfully uninstalled CherryPy-3.2.2
  Running setup.py install for cherrypy
    changing mode of build/scripts-2.7/cherryd from 644 to 755
    changing mode of /usr/bin/cherryd to 755
Successfully installed cherrypy-3.2.3


well i installed it with pip now

still :
[root@mshade ~]# service mineos start
Traceback (most recent call last):
  File "/usr/games/minecraft/server.py", line 11, in <module>
    import cherrypy
ImportError: No module named cherrypy

**Comment by hexparrot** [comment]
I had no issue installing MineOS on a new copy of CentOS7.

I did the following commands from a completely fresh install, with sshd up:

    1  yum update
    2  yum install wget
    3  wget https://gist.github.com/hexparrot/7237456/raw
    4  chmod +x raw
    5  ./raw
    6  history

My best guess is that you didn't install a parallel version of Python, as the instructions recommended?

If not, you may not then have yours configured as the script expects "./configure --prefix=/usr/local", and /usr/local is also present in the /etc/init.d/mineos script.

**Comment by xzero121** [comment]
I don't know if anyone else is having this problem but I keep running into the exact same issue, and i don't really see a resolution here? Did you use Minimal install? I followed these directions line by line after a clean install two separate times and I continue to get the exact same error message. Care to troubleshoot?
