### ISSUE TITLE
Server list not showing

### ISSUE THREAD

**Issue by mcfilip** [hexparrot/mineos#110]
Hello, i have 0.6.0 version of MineOS
but when i add servers it just wont show in dashboard..
http://prntscr.com/6q05bw
I rebooted but no sense.. please help and best regards!

**Comment by hexparrot** [comment]
In the future, not blotting out information might help find a resolution faster.  For example, you have installed the web-ui....what distro?  Did you ever try updating the web-ui using the instructions from the wiki?

What commit (webui version) were you using?
