### ISSUE TITLE
/init/minecraft fails to start server on boot

### ISSUE THREAD

**Issue by grit96** [hexparrot/mineos#111]
Running Ubuntu 14.04

`/init/minecraft` runs because the logs show up in `/var/log/mineos.log`

After the system has booted, the server has not been started:
```
# service minecraft status
 * MineOS Server Status                                                                                 
Dvbris: False
```

Running `service minecraft start` manually works:
```
# service minecraft start 
 * Starting MineOS servers...                                                                           
starting Dvbris...  done

# service minecraft status
 * MineOS Server Status                                                                                 
Dvbris: True
```

The server is set to start on boot:
```
>>> from mineos import mc
>>> mc.list_servers_start_at_boot('/var/games/minecraft')
['Dvbris']
```

**Comment by hexparrot** [comment]
If you run the command "service --status-all", do you see both minecraft and mineos listed?

If not, you may have accidentally missed the service-adding command from the installation process:

chmod 744 /etc/init.d/minecraft
update-rc.d minecraft defaults

**Comment by grit96** [comment]
`service --status-all` gives the output:
```
 [ ? ]  minecraft
 [ ? ]  mineos
```

**Comment by hexparrot** [comment]
Unsure if you've tested the previous recommendation of checking chmod and re-running the commands to get the initscripts running.  Closing for now, but if the problem persists, I'd be happy to go further into it and see what went wrong; as of now, it seems the wiki instructions still work on 14.04.
