### ISSUE TITLE
Systemd Support

### ISSUE THREAD

**Issue by xd1936** [hexparrot/mineos#115]
I installed MineOS on [Ubuntu 15.04](https://wiki.ubuntu.com/SystemdForUpstartUsers) and [Debian 8](https://wiki.debian.org/systemd)... both of which now have systemd instead of upstart as their init manager. I followed [the apt-get instructions on the wiki](http://minecraft.codeemo.com/mineoswiki/index.php?title=MineOS_(apt-get)) without trouble, but when it came to actually using MineOS... no such luck. MineOS is listed in `service --list-all` as running, but I cannot connect as I normally would be able to.

Following the same steps in Ubuntu 14.04 (which still uses upstart, not systemd), everything works as expected.

I don't know if the init scripts need to be updated, or the apt-get instructions on the wiki.

**Comment by xd1936** [comment]
If I were to follow the [Arch instructions](http://minecraft.codeemo.com/mineoswiki/index.php?title=MineOS_(pacman)) when it comes to setting up the systemd service, would that work?

`cp /usr/games/minecraft/init/mineos.arch /etc/systemd/system/mineos.service`
`systemctl enable mineos.service`

`cp /usr/games/minecraft/init/minecraft.arch /etc/systemd/system/minecraft.service`
`systemctl enable minecraft.service`

**Comment by hexparrot** [comment]
I suspect it would; give it a shot.  Let me know if you're able to get it up and running with these instructions and I'll update the wiki.

**Comment by hexparrot** [comment]
Were you able to make it work with the instructions taken from Arch?

**Comment by xd1936** [comment]
I gave it a shot and wasn't having any luck, but I'm not entirely confident in the process I used. I don't have any bare-metal hardware to test with, and tried this in a VM. It didn't seem to be working, but something screwy may have been happening with Virtualbox Networking.

Does anyone else have a spare piece of hardware to test this with?

**Comment by kaimi** [comment]
You did do a `systemctl start mineos.service`, right?

**Comment by hexparrot** [comment]
Confirm it works on Ubuntu 15.04.

Problem: Ubuntu 15.04 updates Cherrypy to a version that is broken with SSL.  See existing issue: http://discourse.codeemo.com/t/solved-ssl-received-a-record-that-exceeded-the-maximum-permissible-length/45

I have created a new wikipage to address this edge case with "MineOS-on-Ubuntu 15", which you can find on the wiki: 

http://minecraft.codeemo.com/mineoswiki/index.php?title=MineOS_(apt-get%2Bsystemd)
