### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos#117]
the config dont fonctionne :/

**Comment by hexparrot** [comment]
not enough information to know what you're talking about.

**Comment by MrBretze** [comment]
i modified the mineos.cfg in /user/games/minecraft/mineos.conf and edit the port and the https option.

I restart mineos by service mineos stop and start.

**Comment by Siliconheart** [comment]
Isn't that file supposed to be edited in `/etc/mineos.conf` ?
 `/user/games/minecraft/mineos.conf` is just a default copy of it, if I remember it right.

**Comment by MrBretze** [comment]
Yes x)
