### ISSUE TITLE
Idea: RAM by user

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos#118]
y use this http://unix.stackexchange.com/questions/34334/how-to-create-a-user-with-limited-ram-usage to set a limit of ram by user. mineos dont use this :/

**Comment by hexparrot** [comment]
What purpose does this address that setting the maximum heap size doesn't already solve?  If the server needs memory, it's going to want to take it; you can *roughly* limit it with XMX (java heapsize) but if it needs more and it can't get it (e.g., java wants more than ulimit), then it outright crashes.  This seems less desirable than just....setting the heapsize and looking after it to make sure it doesn't run rampant and/or leak.

**Comment by kaimi** [comment]
Instead of full-blown virtual machines, you might want to have a look at [LXC](https://linuxcontainers.org/).

**Comment by hexparrot** [comment]
While LXC is a great option, the largest problem with them is the increased amount of complexity they add to users who may not be as command-line saavy.  With a virtual machine, more novice users get the benefit of a familiar-feeling GUI (yes, on a host machine with a gui there's resources lost) for ease of deployment.

LXC, awesome as it is (like docker and freebsd jails), involve kernels, kernel configs, and lots of command-line fu that turn a mostly solved problem (memory limiting with vms) into a real hurdle for green Linux users (which is the vastly overwhelming audience behind MineOS).

Of course, I might be projecting too much--LXC is a great solution for what the OP is asking, but know it is rather involving!

**Comment by kaimi** [comment]
You’re right, but they’re actually easy to setup using `libvirt`, and `libvirt-manager` is a GUI tool ;)
