### ISSUE TITLE
Resource pack ?

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos#119]
is possible to add the resource pack in the server.properties.

**Comment by hexparrot** [comment]
server.properties is readily editable and any attribute you please can be added through the webui.  On the left side of the server.properties page, add "Resource-pack" (or any attribute name you wish to add), and on the corresponding right text box, you put the URL.

Either that or the file can be edited in command line, etc. What are you asking, specifically?

**Comment by MrBretze** [comment]
the changes made to "resource pack" are not saved.

http://i.gyazo.com/e383b7bc853cb2fc95933d5b37a391e3.gif

**Comment by MrBretze** [comment]
we don't really see http://i.gyazo.com/f9d6731b398ce8e40da3e825672c1122.png

**Comment by hexparrot** [comment]
do you hit 'enter' after typing in the values?

**Comment by MrBretze** [comment]
I tested by hitting 'enter' and it works

**Comment by MrBretze** [comment]
thank you
