### ISSUE TITLE
Idea: Restart option

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos#121]
Hello, please a restart button :/

**Comment by hexparrot** [comment]
I'll welcome any Pull requests with code to do this, but I am no longer coding for the Python-based MineOS.  The NodeJS-based MineOS already has restart functionality.

**Comment by MrBretze** [comment]
The is better ?
Compatible with the Python version ?

**Comment by hexparrot** [comment]
it is a whole new rewrite in a whole new language.  While it will eventually just outright replace the Python version you're using, I don't recommend people "upgrade"--but rather learn and install the new webui on a fresh system first.  I need testing feedback before it shows up on the official ISO.

**Comment by MrBretze** [comment]
Ok tanks :)
