### ISSUE TITLE
cant create profiles

### ISSUE THREAD

**Issue by kieeps** [hexparrot/mineos#124]
So i had to reinstall MineOS due to server problems, and when i loged in to create the profile for forge i got the "Server did not respond to the request"

I ran the javascript console and found this in the log:
http://pastebin.com/E55KhCzp

Anyone know what might have happened?

**Comment by hexparrot** [comment]
Best guess based on that error log is that you created a profile that somehow is having a hard time being parsed.  You can try manually deleting the lines that define the profile in /var/games/minecraft/profiles/profile.config, which should likely solve this problem.

Before you do so, let us know what exactly you have in the profiles.config so we can see what was the problem.

**Comment by kieeps** [comment]
The profile config was empty,  it was fixable by chmod 777 :-P so i probably messed up the permissions somehow,  ended up just reinstalling it anyway :-)  now it works as intended again ;-)

**Comment by hexparrot** [comment]
You typically don't want to just 777 files; that gives read *and* write permissions to all users.  Under normal circumstances, only the owner and group require those, so 664 is probably more appropriate for your blanket chmod.

**Comment by kieeps** [comment]
I know :-) only do 777 to rule out perm problems ;-)
