### ISSUE TITLE
Config Request - Ability to Auto Prune Restore Points

### ISSUE THREAD

**Issue by vengent** [hexparrot/mineos#129]
Can we get the ability to add auto pruning to restore points?

**Comment by vengent** [comment]
Update, specifically mean this on node.js.  I see it may be available in python.  But i'm running turnkey on node.js

Thanks and love the software!

**Comment by hexparrot** [comment]
Clarify--are you interested in this for mineos-node?  If so, please create the git issue in the appropriate repository.

**Comment by vengent** [comment]
Correct, sorry, thought this was the correct one!
