### ISSUE TITLE
Cant use webui on Turnkey after updating to java 8

### ISSUE THREAD

**Issue by Dennis000903** [hexparrot/mineos#132]
I got Mineos Turnkey to work on my Laptop (64Bit), but I want to use some mods that require Java8, so I decided to update. I deleted old java versions and got after a few tries now Java 8 installed with apt-get, but since I deleted the old java the WebUI isn't working anymore. I think java may be the problem, so the webui is using java? I already restarted it a few times but it doesnt work.. 

I think you may help me so - Any ideas?

**Comment by hexparrot** [comment]
MineOS uses whichever java is found first in the `PATH` argument of your `root` user.  This path is set by the package that installs Java.  Try this:  from the command line, log in as `root` and type in "which java".  This is the method MineOS uses to locate java.  If typing `which java` returns no results, it means however you installed your Java is incomplete.  If there's no results, you also should expect simply typing `java` to not actually find the binary. 

Let me know what the results of your `which java` is.

**Comment by Dennis000903** [comment]
This is what happens in my console:

root@core:~# which java                                                                                                                                                                       
root@core:~# 

It just turns out nothing... How do I solve this? Can I set the Javapath manually?

**Comment by hexparrot** [comment]
You'll need to find out where your `java` was installed.  Once you found out where it was installed, you can add the directory containing `java` (probably in a /bin/ subdirectory) to the path.

http://unix.stackexchange.com/a/26059/16421

**Comment by Dennis000903** [comment]
I found out my path and put it in my ~/.profile like it's in the link, the file now looks like that:

# ~/.profile: executed by the command interpreter for login shells.                          
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login                      
# exists.                                                                                    
# see /usr/share/doc/bash/examples/startup-files for examples.                               
# the files are located in the bash-doc package.                                             
                                                                                             
# the default umask is set in /etc/profile                                                   
#umask 022                                                                                   
                                                                                             
. /etc/profile                                                                               
                                                                                             
# if running bash                                                                            
if [ -n "$BASH_VERSION" ]; then                                                              
    # include .bashrc if it exists                                                           
    if [ -f "$HOME/.bashrc" ]; then                                                          
        . "$HOME/.bashrc"                                                                    
    fi                                                                                       
fi                                                                                           
                                                                                             
# set PATH so it includes user's private bin if it exists                                    
if [ -d "$HOME/bin" ] ; then                                                                 
    PATH="$HOME/bin:$PATH:/usr/lib/jvm/java-8-oracle:/usr/lib/jvm/java-8-oracle/bin"         
fi                                                                                           
                                                                                             
if [ -d $HOME/.profile.d ]; then                                                             
                                                                                             
    for script in $HOME/.profile.d/*; do                                                     
        [ -x "$script" ] || continue                                                         
        . $script                                                                            
    done                                                                                     
                                                                                             
fi                                                                                           
                                                                                             
   

I rebooted a few times but it still dont work... Any ideas?

**Comment by Dennis000903** [comment]
Okay I finally managed to set my JAVA_HOME!

I used this: http://askubuntu.com/questions/175514/how-to-set-java-home-for-java

If I type 
echo $JAVA_HOME
now, it outputs me the correct path: /usr/lib/jvm/java-8-oracle

But I still cant open my Web-UI! Whats wrong?

**Comment by Dennis000903** [comment]
Okay I finally got it working. I reinstalled MineOS completely and installed java8 then without deleting the old java.
