### ISSUE TITLE
Server Restart improvement

### ISSUE THREAD

**Issue by portapipe** [hexparrot/mineos#143]
Hi.
I'm using MineOS since a year now and I've scheduled a restart_interval every 24 hours.
The restart time is midnight and for me is not good because I have lots of people playing during that hours, it should be cool to set the default time of restart.
PLUS when it restart the server it doesn't restart it as expected, it stay down for 30 minutes THEN it start the server correctly.
This problem can be achieved with spigot 1.8.x. I've even created the start.sh file as suggested in several forums (with a second file that is called on restart) but without success.
What should I do to make all these stuff work well?

Thank you very much.

**Comment by portapipe** [comment]
Actually the restart stuff Is working, you MUST set, via terminal, the chmod to a+x of every .sh in the servers:
(cd into your minecraft MineOS folder)
`chmod a+x *.sh -R`
and the miners console too:
`chmod a+x mineos_console.py`
This should be helpful to someone.

Waiting for the night restart to see if it will work. Let see what you're think about manually set the restart time 😄

**Comment by Siliconheart** [comment]
If your .sh script does work for you, disable restarts in MineOS and schedule a cron job to run the script:
https://www.debian-administration.org/article/56/Command_scheduling_with_cron

**Comment by portapipe** [comment]
Oh ok, I thought it should be possible to add it directly to MineOS. Let's see, thanks for the advise 😃
