### ISSUE TITLE
[QUESTION] Start.sh

### ISSUE THREAD

**Issue by maxlehot1234** [hexparrot/mineos#146]
HI, I have a small question...
I know there is few tickets on this here, but I don't know how to do this...
Where I need to put scripts?
Any way to use a simply start.sh script directly when a server stop instead of use differents scripts ?

Thanks again

**Comment by hexparrot** [comment]
Can you clear up what you're asking?  For the most part, MineOS and startup scripts aren't really meant to work together--after all, MineOS is the program that's supposed to start up the server (usually a Java jar) with the arguments you fill in the webui. 

Using a startup script will ignore all webui settings and also not be interact-able for commands such as start/stop. Can you clarify your intents?

**Comment by maxlehot1234** [comment]
Thanks for your answer, but I just want to know how I can force mineos to restart crash server..
So if a server crash, 10-15 seconds after, mineos restart it...


How I can do this?
I have a limited access to all my files. My hosting fault XD


Thank you so much

**Comment by hexparrot** [comment]
How does MineOS know whether Minecraft crashed or was intentionally closed?
