### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ucraft02** [hexparrot/mineos#160]
please help with this
http://prntscr.com/h119kj

**Comment by hexparrot** [comment]
Does your Linux system have `screen` installed?

**Comment by ucraft02** [comment]
I don't now

**Comment by hexparrot** [comment]
1) _did the error change?

2) Have you considered using mineos-node?  This `mineos` repo works with a project that hasn't been updated in several years; `mineos-node` is current, and still receives developmental updates and bugfixing.
