### ISSUE TITLE
I get this error when checking logs

### ISSUE THREAD

**Issue by JordanPlayz158** [hexparrot/mineos#161]
"The server has been generating logs beyond the rate-limit threshold. Log tailing has stopped and can be re-enabled by refreshing the webui."

So I would like to know if I can increase the rate-limit threshold because i've looked at the config for the html but there appears to be no option to set it up higher

**Comment by hexparrot** [comment]
This error is actually only for the mineos-node version of the webui.  Specifically, it points to this line:

https://github.com/hexparrot/mineos-node/blob/master/html/js/scriptin.js#L815

80 messages per second, sustained for 2 seconds is the default.  Can be changed to any value you'd like, but keep in mind, receiving and displaying a whole bunch of logs affects the webui's fluidity/operation, so be mindful of how high you put it.
