### ISSUE TITLE
website down, (codeemo) causing my server to not function 

### ISSUE THREAD

**Issue by Xplodin** [hexparrot/mineos#162]
nvm website is just down or acting up.
My server is bugged cause of other reasons i believe. but not functioning the same as it used to be

**Comment by hexparrot** [comment]
Sorry about this.  Catastrophic failure on the website server caused this acting up.  I suppose I mis-handled how it should operate when the website went down.  The new version of the webui (mineos-node) handled it a-ok, but evidently I wasn't as diligent as I should've been when I wrote this python code nearly 7 years ago. Sorry!
