### ISSUE TITLE
Server not start on Mineos after crash

### ISSUE THREAD

**Issue by achencraft** [hexparrot/mineos#165]
Hi,

I have a minecraft server on spigot 1.14.
This server worked correctly in MineOs before we crash it with worldedit (too big //cut ...)

Since this event, we can't start the server from MineOs Webui.

If I run this command on debian, the minecraft server starts correctly :
`/usr/bin/java -Xmx2000M -Xms256M -jar spigot-1.14.jar `

But nothing in MineOs :/

Someone has an idea to resolve this problem ?

Thanks

**Comment by hexparrot** [comment]
Most common cause for this is inadvertently running the Minecraft server as a non-`mc` user, such as `root`.

This changes ownership of many of the server files, making it unrunnable as `mc` as it once was.  Verify with `ls -la /var/games/minecraft/servers/servername`.  All files should be owned by `mc:mc`, if not, `chown` it back and try again.

**Comment by achencraft** [comment]
Hi !
Ok so I check files permissions

servers was owned by mc user
but archive/profiles/backup ... directory by root

So I change it to mc user, and it works.

I will explain to my partner what was his mistake :)
Thank you !
