### ISSUE TITLE
Mineos Forge

### ISSUE THREAD

**Issue by czadikem** [hexparrot/mineos#166]
I install and run forge but, I cannot connect to it and it does not run correctly.  here are the logs [https://pastebin.com/4TAAiFqK](https://pastebin.com/4TAAiFqK)

**Comment by hexparrot** [comment]
Present in your logs:

```
[19:15:04] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[19:15:04] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: The server will make no attempt to authenticate usernames. Beware.
```

'Offline mode' doesn't sound right, so this could be something you look at; this seems not like a MineOS issue but a configuration of your server.

Or maybe more importantly, these additional concerns:

```
Starting Minecraft server on 0.0.0.0:25566
````

Non-standard port, are you typing in 25566 in your client?  Did you open this non-standard port in the firewall?

**Comment by czadikem** [comment]
That is because I have someone on the server who is a cracked player

**Comment by czadikem** [comment]
I see this error `[19:14:54] ain/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing`

**Comment by czadikem** [comment]
so the port was the issue but how do I run two servers on that port then

**Comment by czadikem** [comment]
Thanks I got it solved just had to use iptables
