### ISSUE TITLE
I dont have the option to create new profiles

### ISSUE THREAD

**Issue by FranciscoTrigo** [hexparrot/mineos#173]
Hello
I want to install Forge for a server, but I do not have the option to create new profiles anywhere in the web ui.
I am using the latest Turnkey release of mineOS.

Where can i find this option/activate?

thanks

**Comment by hexparrot** [comment]
The latest Turnkey release of MineOS refers to this repo instead: https://github.com/hexparrot/mineos-node

Long story short, profiles in _that_ repo are filled into `profiles.js` which define the external resources (URI), and how to populate and display those resources in the webui using the sorting/filter functions.

Profiles are definitely user-creatable, but admittedly it will require javascript knowledge and a bit of testing--it's not simply the URIs that get punched in (though there is an example of that, if you review the code surrounding "nukkit")
