### ISSUE TITLE
A lot of proccesses for each server

### ISSUE THREAD

**Issue by DeathlyFlags** [hexparrot/mineos#91]
I don't know why but MineOS create a lot of proccesses for each server. Consuming all the ram on the machine.

Here you have a screenshot:
http://prntscr.com/5tz1q2

**Comment by Siliconheart** [comment]
1. That's kinda normal: [some screenshots](https://www.google.com/search?q=minecraft+server+htop&newwindow=1&safe=off&espv=2&biw=1920&bih=919&source=lnms&tbm=isch&sa=X&ei=x-e7VIKiIsf7ygPe5IGYBA&ved=0CAcQ_AUoAg&dpr=1)
2. On your screenshot half of RAM is free. (See 'Mem' on top)
3. I counted about 6 MC servers running, with -Xmx from 0,5 to 3 gigs, and they could eat much more, if there is a lot of plugins and players online.
4. Don't sum all processes RAM usage, only main process of each server counts.

**Comment by DeathlyFlags** [comment]
I must say that after killing some of those procs the panel show that I had 15GB of Ram instead of the 200mb at the time of the screenshot.

**Comment by Siliconheart** [comment]
1. I wouldn't kill threads of server if I were you.
2. These yellow sticks in htop are RAM used for disk-cache. MineOS show free RAM, disk-cache is not considered free, but technically it can be freed for another process, if needed. Disk-cache is for performance boost (like temporary RAM-disk) Actual RAM usage is the first number in 'Mem' line of htop (without cache).
3. Calculate a sum of all running servers ram usage found on MineOS' dashboard (first number) to get actual RAM usage of servers.
4. If htop confusing you, try another utilities, like `free -h` or `ps -aux`
5. Press F5 in htop to switch to tree-view. It shows what process call what. MineOS creates a detached screen instance for each server once. All other are threads are created by MC server to utilize multi-core environment, I think. [Read here](https://woodycraft.net/threads/why-is-spigot-bukkit-not-multithreaded.14072/) and [here](http://www.spigotmc.org/threads/multithreading-some-threads.49/) about threads.
6. Read [this](http://www.sk89q.com/2013/03/improving-your-minecraft-servers-performance/) article to clear some things out.
7. If there's no red values in 'virt' and 'res' columns and green sticks in htop's Mem line are not almost on right side - you have nothing to worry about.

**Comment by hexparrot** [comment]
I second the statements from @Siliconheart.  For starters, you want to be wary of EVER killing anything unless there's a problem...and at least from what the screenshot shows, there is none readily apparent.

As shown, the memory is at 14/32GB, which is nothing to be alarmed about.  Your load average over time is 5.14, which is fewer than your available cores (8).  

So the most important question is "is there a problem with the server needing to be addressed...or are you concerned that there is 'too much ram being used'?

As you answer that question, consider these details as well:

1. You're running 6 (or more) servers on this machine. If you're experiencing slowdowns, have you considered HDD bottleneck?
2. You're manually setting XMS lower than XMX in pretty much all cases.  This is not the default behavior of MineOS (which sets XMX==XMS).  Are you familiar with the performance ramifications of doing this?
3. Why do you want there to be 'available' ram, anyway?  Isn't the purpose of the system memory to be available--even if used to cache--to prevent HDD reading where possible?
