### ISSUE TITLE
No console output for older versions.

### ISSUE THREAD

**Issue by thomas15v** [hexparrot/mineos#95]
Somehow it isn't reading from server.log. And its a 1.4.7 forge server I am using.

**Comment by Siliconheart** [comment]
I think MineOS looks for another file, named [ForgeModLoader-server-0.log](https://github.com/hexparrot/mineos/blob/a90b1b14042ecc03f2346520061976f08bd5d822/mineos.py#L96) in case of forge.

**Comment by hexparrot** [comment]
MineOS looks for, in order, the following logs and when it locates one, presents that file and only that file:

proxy.log.0 (bungee)
logs/latest.log (vanilla current)
ForgeModLoader-server-0.log (forge)
server.log (vanilla legacy)

If it is presenting the wrong file (e.g., the file is empty, etc.), let us know *what your intended* server log file should be and whether any of the files before it exist.  If so, it should be as easy as just removing it.

**Comment by thomas15v** [comment]
Hmmm well the ForgeModLoader-server-0.log is useless. It only shows loaded this mods and than it stops. So far I know ForgeModLoader logs aren't relevant to console output, on all minecraft versions..

**Comment by hexparrot** [comment]
I removed ForgeModLoader-server-0.log from the console candidates.  It should now skip it and fallback on server.log.  Update your scripts and that should solve it.

**Comment by thomas15v** [comment]
Thanks :smile:.
